name: management

services:
  watchtower:

    image: containrrr/watchtower
    restart: always
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_CLEANUP: false
      WATCHTOWER_INCLUDE_STOPPED: true
      WATCHTOWER_INCLUDE_RESTARTING: true
      TZ: America/New_York
      WATCHTOWER_ROLLING_RESTART: true
      WATCHTOWER_SCHEDULE: "0 0 6 * * *"
    
  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    container_name: portainer
    ports:
      - "9000:9000"
  