name: automation

services:

  caddy:
  
    image: caddy:latest
    labels:
      - io.portainer.accesscontrol.public
    restart: unless-stopped
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./etc/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
  n8n:
  
    image: n8nio/n8n:latest
    labels:
      - io.portainer.accesscontrol.public
    restart: always
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=n8n.moodybridge.local
      - N8N_PORT=5678
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_SECURE_COOKIE=false
    volumes:
      - n8n_data:/home/node/.n8n

volumes:

  n8n_data:
  caddy_data:
  